services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: lacsc
      POSTGRES_USER: lacsc
      POSTGRES_PASSWORD: lacsc123
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./lacs2026-dev-realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "4089:8080"
    command:
      - start-dev
      - --import-realm
    depends_on:
      - postgres
   
volumes:
  postgres-data: